# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - x500_group_controller

  x500_group_controller:
    type: FollowJointTrajectory
    joints:
      - virtual_joint